In [5]:
import pandas as pd
import requests

In [6]:
#크롤링 할 웹 URL 
page_no = 1

page_url = f'https://finance.naver.com/sise/sise_index_day.naver?code=KPI200&page={page_no}'

#
source = requests.get(page_url).text

In [7]:
source

'<html lang="ko">\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">\n<title>네이버 증권</title>\n\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/newstock.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/common.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/layout.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/main.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/newstock2.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/newstock3.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/world.css">\n</head>\n<body>\n<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/jindo.min.ns.1.5.3.euckr.js"></script>\n<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/lcslog.js"></script>\n\t\t\t\t<!-- 일별시세 -->\n\t\t\t\t<div class="box_type_m">\n\t\t\t\t\t<h4 class="top_tlt" style="text-align:left;"><em>일별</em>시세</h4>\n\t\t\t\t\t<table summary="일별 시세표:날짜에 따른 체결가 전일비 등락률 거래량 거래대금 정보를 제공합니다." cellpadding="0" cellspacing="0" class="type_1">\n\t\t\t\t\t<caption>일별시세</caption>\n\t\t\t\t\t<col width="15%"><col width="14%"><col width="18%"><col width="14%"><col width="*"><col width="18%">\n\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<th>날짜</th>\n\t\t\t\t\t\t\t<th>체결가</th>\n\t\t\t\t\t\t\t<th>전일비</th>\n\t\t\t\t\t\t\t<th>등락률</th>\n\t\t\t\t\t\t\t<th>거래량<span class="add_txt">(천주)</span></th>\n\t\t\t\t\t\t\t<th>거래대금<span class="add_txt">(백만)</span></th>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t<tr><td colspan="6" class="blank_07"></td></tr>\n\n\t\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td class="date">2023.04.14</td>\n\t\t\t\t\t\t<td class="number_1">333.68</td>\n\t\t\t\t\t\t<td class="rate_down" style="padding-right:35px;">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t0.59\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1">\n\t\t\t\t<span class="tah p11 red01">\n\t\t\t\t+0.18%\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:40px;">294,812</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:30px;">9,210,558</td>\n\t\t\t\t\t</tr>\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td class="date">2023.04.13</td>\n\t\t\t\t\t\t<td class="number_1">333.09</td>\n\t\t\t\t\t\t<td class="rate_down" style="padding-right:35px;">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t1.00\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1">\n\t\t\t\t<span class="tah p11 red01">\n\t\t\t\t+0.30%\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:40px;">172,637</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:30px;">8,644,092</td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td class="date">2023.04.12</td>\n\t\t\t\t\t\t<td class="number_1">332.09</td>\n\t\t\t\t\t\t<td class="rate_down" style="padding-right:35px;">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t1.22\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1">\n\t\t\t\t<span class="tah p11 red01">\n\t\t\t\t+0.37%\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:40px;">252,055</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:30px;">10,197,042</td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr><td colspan="6" class="blank_08"></td></tr>\n\t\t\t\t\t<tr><td colspan="6" class="division_line"></td></tr>\n\t\t\t\t\t<tr><td colspan="6" class="blank_08"></td></tr>\n\t\t\t\t\t<tr>\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td class="date">2023.04.11</td>\n\t\t\t\t\t\t<td class="number_1">330.87</td>\n\t\t\t\t\t\t<td class="rate_down" style="padding-right:35px;">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t4.49\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1">\n\t\t\t\t<span class="tah p11 red01">\n\t\t\t\t+1.38%\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:40px;">148,445</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:30px;">9,945,339</td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td class="date">2023.04.10</td>\n\t\t\t\t\t\t<td class="number_1">326.38</td>\n\t\t\t\t\t\t<td class="rate_down" style="padding-right:35px;">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t3.02\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1">\n\t\t\t\t<span class="tah p11 red01">\n\t\t\t\t+0.93%\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:40px;">144,408</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:30px;">8,966,999</td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td class="date">2023.04.07</td>\n\t\t\t\t\t\t<td class="number_1">323.36</td>\n\t\t\t\t\t\t<td class="rate_down" style="padding-right:35px;">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t5.54\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1">\n\t\t\t\t<span class="tah p11 red01">\n\t\t\t\t+1.74%\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:40px;">137,011</td>\n\t\t\t\t\t\t<td class="number_1" style="padding-right:30px;">7,834,873</td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\n\t\t\t\n\t\n\t\n\t\n\t\n\n\t\t\t\t\t<tr><td colspan="6" class="blank_09"></td></tr>\n\t\t\t\t\t<tr><td colspan="6" class="division_line"></td></tr>\n\t\t\t\t\t</table>\n\t\t\t\t<!--- 페이지 네비게이션 시작--->\n\t\t\t\t<table summary="페이지 네비게이션 리스트" class="Nnavi" align="center">\n\t\t\t\t<caption>페이지 네비게이션</caption>\n\t\t\t\t<tr>\t\t\n\t\t\t\n\t\t\t\t\n                \n                <td class="on">\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=1"  >1</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=2"  >2</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=3"  >3</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=4"  >4</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=5"  >5</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=6"  >6</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=7"  >7</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=8"  >8</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=9"  >9</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=10"  >10</a>\n\t\t\t\t</td>\n\n                <td class="pgR">\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=11"  >\n\t\t\t\t다음<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3" height="5" alt="" border="0">\n\t\t\t\t</a>\n\t\t\t\t</td>\n\n                <td class="pgRR">\n\t\t\t\t<a href="/sise/sise_index_day.naver?code=KPI200&amp;page=713"  >맨뒤\n\t\t\t\t<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8" height="5" alt="" border="0">\n\t\t\t\t</a>\n\t\t\t\t</td>\n\n            \n\t\t\t\t</tr>\n\t\t\t\t</table>\n\t\t\t\t<!--- 페이지 네비게이션 끝--->\n\t\t\t\t</div>\n\t\t\t\t<!-- //일별시세 -->\n\t\t\t\t\n<script type="text/javascript">\n    ;(function(){\n        var eventType = "onpageshow" in window ? "pageshow" : "load";\n        jindo.$Fn(function(){\n            lcs_do();\n        }).attach(window, eventType);\n    })();\n</script>\n\n</body>\n</html>\n'

In [10]:
# beautifulsoup4를 불러온다.

import bs4

In [87]:
source = bs4.BeautifulSoup(source)

In [88]:
print(source.prettify())

<html lang="ko">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   네이버 증권
  </title>
  <link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/newstock.css" rel="stylesheet" type="text/css"/>
  <link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/common.css" rel="stylesheet" type="text/css"/>
  <link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/layout.css" rel="stylesheet" type="text/css"/>
  <link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/main.css" rel="stylesheet" type="text/css"/>
  <link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/newstock2.css" rel="stylesheet" type="text/css"/>
  <link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/newstock3.css" rel="stylesheet" type="text/css"/>
  <link href="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/css/world.css" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <script src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/jindo.min.ns.1.5.3.euckr.js" type="text/javascript">
  </script>
  <script src="https://ssl.pstatic.net/imgstock/static.pc/20230321170048/js/lcslog.js" type="text/javascript">
  </script>
  <!-- 일별시세 -->
  <div class="box_type_m">
   <h4 class="top_tlt" style="text-align:left;">
    <em>
     일별
    </em>
    시세
   </h4>
   <table cellpadding="0" cellspacing="0" class="type_1" summary="일별 시세표:날짜에 따른 체결가 전일비 등락률 거래량 거래대금 정보를 제공합니다.">
    <caption>
     일별시세
    </caption>
    <col width="15%"/>
    <col width="14%"/>
    <col width="18%"/>
    <col width="14%"/>
    <col width="*"/>
    <col width="18%"/>
    <tr>
     <th>
      날짜
     </th>
     <th>
      체결가
     </th>
     <th>
      전일비
     </th>
     <th>
      등락률
     </th>
     <th>
      거래량
      <span class="add_txt">
       (천주)
      </span>
     </th>
     <th>
      거래대금
      <span class="add_txt">
       (백만)
      </span>
     </th>
    </tr>
    <tr>
     <td class="blank_07" colspan="6">
     </td>
    </tr>
    <tr>
     <td class="date">
      2023.04.14
     </td>
     <td class="number_1">
      333.70
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       0.61
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +0.18%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      285,108
     </td>
     <td class="number_1" style="padding-right:30px;">
      8,713,165
     </td>
    </tr>
    <tr>
     <td class="date">
      2023.04.13
     </td>
     <td class="number_1">
      333.09
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       1.00
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +0.30%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      172,637
     </td>
     <td class="number_1" style="padding-right:30px;">
      8,644,092
     </td>
    </tr>
    <tr>
     <td class="date">
      2023.04.12
     </td>
     <td class="number_1">
      332.09
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       1.22
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +0.37%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      252,055
     </td>
     <td class="number_1" style="padding-right:30px;">
      10,197,042
     </td>
    </tr>
    <tr>
     <td class="blank_08" colspan="6">
     </td>
    </tr>
    <tr>
     <td class="division_line" colspan="6">
     </td>
    </tr>
    <tr>
     <td class="blank_08" colspan="6">
     </td>
    </tr>
    <tr>
    </tr>
    <tr>
     <td class="date">
      2023.04.11
     </td>
     <td class="number_1">
      330.87
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       4.49
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +1.38%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      148,445
     </td>
     <td class="number_1" style="padding-right:30px;">
      9,945,339
     </td>
    </tr>
    <tr>
     <td class="date">
      2023.04.10
     </td>
     <td class="number_1">
      326.38
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       3.02
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +0.93%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      144,408
     </td>
     <td class="number_1" style="padding-right:30px;">
      8,966,999
     </td>
    </tr>
    <tr>
     <td class="date">
      2023.04.07
     </td>
     <td class="number_1">
      323.36
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       5.54
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +1.74%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      137,011
     </td>
     <td class="number_1" style="padding-right:30px;">
      7,834,873
     </td>
    </tr>
    <tr>
     <td class="blank_09" colspan="6">
     </td>
    </tr>
    <tr>
     <td class="division_line" colspan="6">
     </td>
    </tr>
   </table>
   <!--- 페이지 네비게이션 시작--->
   <table align="center" class="Nnavi" summary="페이지 네비게이션 리스트">
    <caption>
     페이지 네비게이션
    </caption>
    <tr>
     <td class="on">
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=1">
       1
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=2">
       2
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=3">
       3
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=4">
       4
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=5">
       5
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=6">
       6
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=7">
       7
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=8">
       8
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=9">
       9
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=10">
       10
      </a>
     </td>
     <td class="pgR">
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=11">
       다음
       <img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3"/>
      </a>
     </td>
     <td class="pgRR">
      <a href="/sise/sise_index_day.naver?code=KPI200&amp;page=713">
       맨뒤
       <img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
      </a>
     </td>
    </tr>
   </table>
   <!--- 페이지 네비게이션 끝--->
  </div>
  <!-- //일별시세 -->
  <script type="text/javascript">
   ;(function(){
        var eventType = "onpageshow" in window ? "pageshow" : "load";
        jindo.$Fn(function(){
            lcs_do();
        }).attach(window, eventType);
    })();
  </script>
 </body>
</html>

In [50]:
# find_all()는 HTML source에서 조건을 만족하는 모든 tag를 가져오는 함수
prices = source.find_all('td', class_='number_1')

In [97]:
dates = source.find_all('td',class_=('date'))

dates.text

AttributeError: ResultSet object has no attribute 'text'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [56]:
price_list = []

for n in prices[::4]:
    price_list.append(n.text)

price_list

['335.05', '333.09', '332.09', '330.87', '326.38', '323.36']

In [66]:
last_url = source.find_all("td",class_="pgRR")[0].find_all("a")[0]["href"]
last_url

'/sise/sise_index_day.naver?code=KPI200&page=713'

In [69]:
last_page = int(last_url.split('&page=')[-1])
last_page

713

In [100]:
price_list = []
date_list = []
for page_no in range(1,last_page+1):
    
    page_url = f'https://finance.naver.com/sise/sise_index_day.naver?code=KPI200&page={page_no}'

    source = requests.get(page_url).text
    
    source = bs4.BeautifulSoup(source)
    source.prettify()
    prices = source.find_all('td', class_='number_1')
    dates = source.find_all('td',class_=('date'))
    
    for date in dates:
        date_list.append(date.text)
        
    for n in prices[::4]:
        price_list.append(n.text)
        
print("end")

end

In [110]:
len(price_list) 
len(date_list)

4278

In [113]:
df = pd.DataFrame({'date' : date_list, 'price' : price_list})
df

            date   price
0     2023.04.14  333.50
1     2023.04.13  333.09
2     2023.04.12  332.09
3     2023.04.11  330.87
4     2023.04.10  326.38
...          ...     ...
4273
4274
4275
4276
4277

[4278 rows x 2 columns]

In [115]:
df.to_excel("kpi200.xlsx",index=False)